### PR TITLE
Update gift-prepaid-subscription-notification.html

### PR DESCRIPTION
**Pull request by avra911**

### CODE REVIEW

**Comment by danhemerlein** [comment]
update the variables to appear like so:

```
gift_pre_paid_subscription:
  redemption_code: ABCD1234
  redemption_url: localhost:3000/redeem/ABCD1234
  gift_note: 'This is a gift from a friend. Enjoy!'
```

**Comment by avra911** [comment]
> update the variables to appear like so:
> 
> ```
> sender:
>   firstname:
>   lastname:
>   
> gift_pre_paid_subscription:
>   redemption_code: ABCD1234
>   redemption_url: localhost:3000/redeem/ABCD1234
>   gift_note: 'This is a gift from a friend. Enjoy!'
>   installment_count: 
>   receiver_name: 
>   variant_options: 
>   options: 
> ```
> 
> you'll be able to get the box size and species from the `variant_options` and `options` keys on the `gift_pre_paid_subscription` object. the interval length of all subscriptions is months so we can hardcode that into the template

hey, @danhemerlein ,

Can you please update with a full example? which exact keys variant options and options will use?

Thanks,
R

**Comment by danhemerlein** [comment]
sure!! please actually use this pattern for drafted variables in the template

```
---
sender:
  firstname: Jane
  lastname: Doe
gift_pre_paid_subscription:
  installment_count: 3
  redemption_code: ABCD1234
  redemption_url: localhost:3000/redeem/ABCD1234
  message: This is a gift from a friend. Enjoy!
  receiver_name: Jane Doe
order:
  image: https://placekitten.com/48/48
  name: Mystery Tackle Box
  options_text: 1 X MYSTERY TACKLE BOX, 6 MONTH PLAN - SPECIES: INSHORE SALTWATER, BOX SIZE: ELITE
  variant_options: SPECIES: INSHORE SALTWATER, BOX SIZE: ELITE
  options: {"SPECIES"=>"INSHORE SALTWATER"}, {"BOX SIZE"=>"ELITE"}
---
```

then the variables can be accessed like this in site the markup of the template

```
<h3 class="text-center">Options Text&nbsp;{{ order.options_text }}</h3>
<h3 class="text-center">
Options Variant&nbsp;{{ order.variant_options }}
</h3>
<h3 class="text-center">Options &nbsp;{{ order.options }}</h3>
```

**Comment by danhemerlein** [comment]
@avra911 I opened a Draft PR which some starter code for the `gift-prepaid-subscription-notification.html` template: 

https://github.com/chordcommerce/chord-emails-template/pull/3/files#diff-e58930b172328fb705f159a9c44a790c931aa5b728400129f1e49468e02f50d3

**Comment by avra911** [comment]
> @avra911 I opened a Draft PR which some starter code for the `gift-prepaid-subscription-notification.html` template:
> 
> https://github.com/chordcommerce/chord-emails-template/pull/3/files#diff-e58930b172328fb705f159a9c44a790c931aa5b728400129f1e49468e02f50d3

hey, @danhemerlein 

Is it the `{"SPECIES"=>"INSHORE SALTWATER"}, {"BOX SIZE"=>"ELITE"}` string accessible so we can display separately the species and the size in two different places? In our design, these information are in separate table rows.

**Comment by danhemerlein** [comment]
> > @avra911 I opened a Draft PR which some starter code for the `gift-prepaid-subscription-notification.html` template:
> > https://github.com/chordcommerce/chord-emails-template/pull/3/files#diff-e58930b172328fb705f159a9c44a790c931aa5b728400129f1e49468e02f50d3
> 
> hey, @danhemerlein
> 
> Is the string {"SPECIES"=>"INSHORE SALTWATER"}, {"BOX SIZE"=>"ELITE"} accessible so we can display the species and size separately in two different places? In our design, this information is in separate rows of the table.

I would recommend iterating over the `order.options` array [like so](https://stackoverflow.com/questions/51357837/loop-through-array-mustache-template-with-key-value-pair) the order that the data comes through in may just be what it is

**Pull request closed without merging**
